### ISSUE TITLE
Multiples of the same clone allowed

### ISSUE THREAD

**Issue by SaeedRazavi** [CalvinKrist/ProjectBrightSun#142]
Cloning a machine multiple times allows machines with the same name to exist.

Ex: 
Machines created:
"Test"

-->"Test" is cloned twice-->

Machines created:
"Test", "Clone_of_Test", "Clone_of_Test"

**Comment by CalvinKrist** [comment]
I have been unable to duplicate this bug on my own machine as directed. If you can find a way to reliably duplicate it, that would be fantastic.
