### ISSUE TITLE
Issue with windows builds where there's a space in box name

### ISSUE THREAD

**Issue by CalvinKrist** [CalvinKrist/ProjectBrightSun#74]
If the box is called something like "main domain controller" the packer build command will be "packer build main domain controller.json", which doesn't work. Name needs to be escaped charactered with \", so the backer build command is 'packer build "main domain controller.json"'

**Comment by ION28** [comment]
part of the reason why I have tried not to support spaces in the naming of boxes yet is because that name also gets set to the computer's hostname in windows builds and it is incredibly bad practice (if not even technically possible) to have spaces in your hostname @CalvinKrist

**Comment by CalvinKrist** [comment]
Then @ION28 we should stop the user from using spaces in the name

**Comment by ION28** [comment]
yup, we'll talk about it more, but that's the route I'm leaning towards

**Comment by CalvinKrist** [comment]
@ION28 Agreed. A nice red box with a message to the user. Very clear, user friendly.
