### ISSUE TITLE
Implement Logo

### ISSUE THREAD

**Issue by SaeedRazavi** [CalvinKrist/ProjectBrightSun#98]
Orange top Yellow bottom gradient circle
White 1's and 0's vertically aligned (The Matrix-esque) fading in from top to bottom (more transparent on top)

**Comment by anilkilic** [comment]
Hey, I tried something. I'm not a huge fan of small details but let me know what do you think.
![screen shot 2018-05-20 at 10 03 37](https://user-images.githubusercontent.com/2311397/40276527-395a8144-5c15-11e8-803f-2e7433f277fc.png)

**Comment by SaeedRazavi** [comment]
Hey, those look great; I think the second design from the left scales nicest. Do you have higher resolution versions?

**Comment by anilkilic** [comment]
Wow, thanks. The idea was there I just tried to apply.
It's vectorial so can be scalable to any size that project requires. 
I exported logomark as separate, I couldn't be sure about the logotype tho.
Again, let me know if you want further changes.

[Drive - Google Drive](https://drive.google.com/drive/folders/1VN1I_WsuHs6tiSWMOFjruQ_pMe__QVCB)

Colors: Orange #f9951c | Yellow #fdcf18
Font: Ubuntu Mono from [Google Fonts](https://fonts.google.com/specimen/Ubuntu+Mono)

**Comment by SaeedRazavi** [comment]
Those are great; thanks for adding value to the project. With your permission, we'll put the logo up and credit you.

**Comment by anilkilic** [comment]
Awesome

If you are asking for some kind of license (by permission). You can use it under creative commons, or whatever your project's license suits. I'm glad that it worked for you, let me know if you need some adjustments or any kind of graphical assets. 

Have a great day.

**Comment by SaeedRazavi** [comment]
Excellent, thank you. 
Have a great day.
